config/routes.rb
Rails.application.routes.draw do

  get "/", :controller => "home", :action => "show"

  get "/competencies/new", :controller => "competencies", :action => "new"
  post "/create_competency", :controller => "competencies", :action => "create"

  get "/competencies", :controller => "competencies", :action => "index"
  get "/competencies/:id", :controller => "competencies", :action => "show"

  get "/competencies/:id/edit", :controller => "competencies", :action => "edit"
  post "/update_competency/:id", :controller => "competencies", :action => "update"

  get "/delete_competency/:id", :controller => "competencies", :action => "destroy"

  get "/goal_notes/new", :controller => "goal_notes", :action => "new"
  post "/create_goal_note", :controller => "goal_notes", :action => "create"

  get "/goal_notes", :controller => "goal_notes", :action => "index"
  get "/goal_notes/:id", :controller => "goal_notes", :action => "show"

  get "/goal_notes/:id/edit", :controller => "goal_notes", :action => "edit"
  post "/update_goal_note/:id", :controller => "goal_notes", :action => "update"

  get "/delete_goal_note/:id", :controller => "goal_notes", :action => "destroy"

  get "/meeting_notes/new", :controller => "meeting_notes", :action => "new"
  post "/create_meeting_note", :controller => "meeting_notes", :action => "create"

  get "/meeting_notes", :controller => "meeting_notes", :action => "index"
  get "/meeting_notes/:id", :controller => "meeting_notes", :action => "show"

  get "/meeting_notes/:id/edit", :controller => "meeting_notes", :action => "edit"
  post "/update_meeting_note/:id", :controller => "meeting_notes", :action => "update"

  get "/delete_meeting_note/:id", :controller => "meeting_notes", :action => "destroy"

  get "/competency_notes/new", :controller => "competency_notes", :action => "new"
  post "/create_competency_note", :controller => "competency_notes", :action => "create"

  get "/competency_notes", :controller => "competency_notes", :action => "index"
  get "/competency_notes/:id", :controller => "competency_notes", :action => "show"

  get "/competency_notes/:id/edit", :controller => "competency_notes", :action => "edit"
  post "/update_competency_note/:id", :controller => "competency_notes", :action => "update"

  get "/delete_competency_note/:id", :controller => "competency_notes", :action => "destroy"

  get "/goals/new", :controller => "goals", :action => "new"
  post "/create_goal", :controller => "goals", :action => "create"

  get "/goals", :controller => "goals", :action => "index"
  get "/goals/:id", :controller => "goals", :action => "show"

  get "/goals/:id/edit", :controller => "goals", :action => "edit"
  post "/update_goal/:id", :controller => "goals", :action => "update"

  get "/delete_goal/:id", :controller => "goals", :action => "destroy"

  devise_for :employees

  root to: 'goals#index'

end

app/models/competency.rb
class Competency < ActiveRecord::Base
  has_many :competency_notes , :class_name => "CompetencyNote", :foreign_key => "competency_id"

  validates :comp_name, :presence => true, :uniqueness => true

end

app/controllers/competencies_controller.rb
class CompetenciesController < ApplicationController
  def index
    @competencies = Competency.all
  end

  def show
    @competency = Competency.find(params[:id])
  end

  def new
    @competency = Competency.new
  end

  def create
    @competency = Competency.new
    @competency.comp_name = params[:comp_name]
    @competency.comp_description = params[:comp_description]

    if @competency.save
      redirect_to "/competencies", :notice => "Competency created successfully."
    else
      render 'new'
    end
  end

  def edit
    @competency = Competency.find(params[:id])
  end

  def update
    @competency = Competency.find(params[:id])

    @competency.comp_name = params[:comp_name]
    @competency.comp_description = params[:comp_description]

    if @competency.save
      redirect_to "/competencies", :notice => "Competency updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @competency = Competency.find(params[:id])

    @competency.destroy

    redirect_to "/competencies", :notice => "Competency deleted."
  end
end

app/views/competencies/edit.html.erb
<!-- Validation failure messages -->

<% if @competency.errors.any? %>
  <% @competency.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Competency #<%= @competency.id %></h3>
      </div>
      <div class="panel-body">
        <form action="/update_competency/<%= @competency.id %>" method="post" class="form-horizontal">
          <!-- Hidden input for authenticity token to protect from forgery -->
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

          <!-- Label and input for comp_name -->
          <div class="form-group">
            <label for="comp_name" class="col-sm-2 control-label">
              Competency name
            </label>
            <div class="col-sm-10">
              <input type="text" id="comp_name" name="comp_name" placeholder="Competency name" class="form-control" value="<%= @competency.comp_name %>">
            </div>
          </div>

          <!-- Label and input for comp_description -->
          <div class="form-group">
            <label for="comp_description" class="col-sm-2 control-label">
              Competency description
            </label>
            <div class="col-sm-10">
              <textarea id="comp_description" name="comp_description" placeholder="Competency description" class="form-control" rows="3"><%= @competency.comp_description %></textarea>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button class="btn btn-warning">
                Update Competency
              </button>
              or
              <a href="/competencies/<%= @competency.id %>">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/competencies/index.html.erb
<div class="page-header">
  <h1>
    Competencies
    <a href="/competencies/new" class="btn btn-lg btn-success"><i class="fa fa-plus"></i></a>
  </h1>
</div>

    <div class="row">
      <div class="col-md-12">
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th>Competency Name</th>
              <th>Competency Description</th>
              <th>View/Add Competency Notes</th>
              <th>Edit Competency</th>
              <th>Delete Competency</th>
            </tr>
          </thead>
          <tbody>
          <% @competencies.each do |competency| %>
            <tr>
              <td><%= competency.comp_name %></td>
              <td><%= competency.comp_description %></td>
              <td>
                <a href="/competencies/<%= competency.id %>" class="btn btn-primary"><i class="fa fa-search-plus"></i></a></td>
              <td>
                <a href="/competencies/<%= competency.id %>/edit" class="btn btn-warning"><i class="fa fa-edit"></i></a></td>
              <td>
                <a href="/delete_competency/<%= competency.id %>" class="btn btn-danger" rel="nofollow"><i class="fa fa-trash-o"></i></a>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

app/views/competencies/new.html.erb
<!-- Validation failure messages -->

<% if @competency.errors.any? %>
  <% @competency.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Competency</h3>
      </div>
      <div class="panel-body">
        <form action="/create_competency" method="post" class="form-horizontal">
          <!-- Hidden input for authenticity token to protect from forgery -->
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

          <!-- Label and input for comp_name -->
          <div class="form-group">
            <label for="comp_name" class="col-sm-2 control-label">
              Competency name
            </label>
            <div class="col-sm-10">
              <input type="text" id="comp_name" name="comp_name" placeholder="Competency name" class="form-control" value="<%= @competency.comp_name %>">
            </div>
          </div>

          <!-- Label and input for comp_description -->
          <div class="form-group">
            <label for="comp_description" class="col-sm-2 control-label">
              Competency description
            </label>
            <div class="col-sm-10">
              <textarea id="comp_description" name="comp_description" placeholder="Competency description" class="form-control" rows="3"><%= @competency.comp_description %></textarea>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button class="btn btn-success">
                Create Competency
              </button>
              or
              <a href="/competencies">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/competencies/show.html.erb
<div class="page-header">
  <h1>
    Competency: <%= @competency.comp_name %>
  </h1>
</div>

<div class="row">
  <div>
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-9">
            <dl class="dl-horizontal">
              <dt>Competency description</dt>
              <dd><%= @competency.comp_description %></dd>
            </dl>
            </div>
            <div class="btn-group-vertical" class="col-md-3">
              <a href="/competencies" class="btn btn-primary">
                <i class="fa fa-chevron-left"> View All Competencies</i>
              </a>
              </a>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
      <!-- Validation failure messages -->
      <% @competency_note = CompetencyNote.new %>

      <% if @competency_note.errors.any? %>
        <% @competency_note.errors.full_messages.each do |message| %>
          <div class="alert alert-dismissable alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= message %>
          </div>
        <% end %>
      <% end %>

        <div>
          <div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Competency Notes</h3>
              </div>
                <div>
                    <table class="table table-striped table-hover ">
                      <thead>
                        <tr>
                          <th>Submitted</th>
                          <th>Competency Note</th>
                          <th>Edit Note</th>
                          <th>Delete Note</th>
                        </tr>
                      </thead>
                      <tbody>
                      <% @competency.competency_notes.each do |notes| %>
                        <tr>
                          <td><%= notes.created_at.strftime('%b %d, %Y') %></td>
                          <td><%= notes.note %></td>
                          <td>
                            <a href="/competency_notes/<%= notes.id %>/edit" class="btn btn-warning"><i class="fa fa-edit"></i></a>
                          <td>
                            <a href="/delete_competency/<%= notes.id %>" class="btn btn-danger" rel="nofollow"><i class="fa fa-trash-o"></i></a>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                </div>

              <div class="panel-body">
                <form action="/create_competency_note" method="post" class="form-horizontal">
                  <!-- Hidden input for authenticity token to protect from forgery -->
                  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

                  <!-- Label and input for employee_id -->
                  <input name="employee_id" type="hidden" value="<%= current_employee.id %>">

                <!-- Label and input for competency_id -->
                <input name="competency_id" type="hidden" value="<%= @competency.id %>">

                <!-- Label and input for note -->
                <div class="form-group">
                  <label for="note" class="col-sm-2 control-label">
                    Note
                  </label>
                  <div class="col-sm-10">
                    <textarea id="note" name="note" placeholder="Note" class="form-control" rows="3"><%= @competency_note.note %></textarea>
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-success">
                      Create Competency Note
                    </button>
                    or
                    <a href="/competencies">Cancel</a>
                  </div>
                </div>
                </form>
              </div>
            </div>
          </div>
        </div>